-- Migration 0003: RBAC Foundation (additive step)
-- DDL generated by Prisma; seed data and data migration added manually.
--
-- What this migration does:
--   1. Adds roles, permissions, and role_permissions tables
--   2. Adds nullable role_id column to users (FK to roles)
--   3. Seeds 3 system roles: SUPER_ADMIN, ADMIN, VIEWER
--   4. Seeds 18 permissions across 4 modules: users, roles, org, audit
--   5. Assigns permissions to each system role per the approved matrix
--   6. Backfills role_id for all existing users from the legacy role enum
--      (UserRole.ADMIN → SUPER_ADMIN, UserRole.USER → VIEWER)
--
-- The legacy role column and user_role enum are NOT removed here.
-- Migration 0004 makes role_id NOT NULL and removes the legacy column/type.
-- Do not run migration 0004 until this migration's data backfill is verified.

-- AlterTable
ALTER TABLE "users" ADD COLUMN     "role_id" UUID;

-- CreateTable
CREATE TABLE "roles" (
    "id" UUID NOT NULL,
    "code" VARCHAR(50) NOT NULL,
    "name" VARCHAR(200) NOT NULL,
    "description" VARCHAR(500),
    "is_system" BOOLEAN NOT NULL DEFAULT false,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "roles_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "permissions" (
    "id" UUID NOT NULL,
    "code" VARCHAR(100) NOT NULL,
    "name" VARCHAR(200) NOT NULL,
    "description" VARCHAR(500),
    "module" VARCHAR(50) NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "permissions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "role_permissions" (
    "role_id" UUID NOT NULL,
    "permission_id" UUID NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "role_permissions_pkey" PRIMARY KEY ("role_id","permission_id")
);

-- CreateIndex
CREATE UNIQUE INDEX "roles_code_key" ON "roles"("code");

-- CreateIndex
CREATE UNIQUE INDEX "permissions_code_key" ON "permissions"("code");

-- CreateIndex
CREATE INDEX "permissions_module_idx" ON "permissions"("module");

-- CreateIndex
CREATE INDEX "users_role_id_idx" ON "users"("role_id");

-- AddForeignKey
ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_permission_id_fkey" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "users" ADD CONSTRAINT "users_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- Integrity constraints (manually added — Prisma does not generate CHECK constraints)
ALTER TABLE "roles"
    ADD CONSTRAINT "roles_code_format_check"
        CHECK ("code" = upper("code") AND "code" ~ '^[A-Z][A-Z0-9_]{1,49}$'),
    ADD CONSTRAINT "roles_name_not_blank_check"
        CHECK (length(btrim("name")) > 0);

ALTER TABLE "permissions"
    ADD CONSTRAINT "permissions_code_format_check"
        CHECK ("code" ~ '^[a-z][a-z0-9]*(\.[a-z][a-z0-9_]*)*$'),
    ADD CONSTRAINT "permissions_name_not_blank_check"
        CHECK (length(btrim("name")) > 0),
    ADD CONSTRAINT "permissions_module_not_blank_check"
        CHECK (length(btrim("module")) > 0);

-- Seed: system roles
-- is_system=true prevents deletion, deactivation, and code changes at the service layer.
INSERT INTO "roles" ("id", "code", "name", "description", "is_system", "is_active", "created_at", "updated_at") VALUES
    (gen_random_uuid(), 'SUPER_ADMIN', 'Super Administrator',
        'Full system access. Can manage roles, permissions, and all system configuration.',
        true, true, now(), now()),
    (gen_random_uuid(), 'ADMIN', 'Administrator',
        'Operational administration access. Can manage users and organization structure.',
        true, true, now(), now()),
    (gen_random_uuid(), 'VIEWER', 'Viewer',
        'Read-only access to approved modules.',
        true, true, now(), now());

-- Seed: permissions (18 permissions across 4 modules)
INSERT INTO "permissions" ("id", "code", "name", "description", "module", "created_at") VALUES
    -- users module (7 permissions)
    (gen_random_uuid(), 'users.read',
        'View Users',
        'List users and view user details.',
        'users', now()),
    (gen_random_uuid(), 'users.create',
        'Create Users',
        'Create new user accounts.',
        'users', now()),
    (gen_random_uuid(), 'users.update',
        'Update Users',
        'Edit user profile fields, excluding role assignment.',
        'users', now()),
    (gen_random_uuid(), 'users.assign_role',
        'Assign User Roles',
        'Assign a role to a user account.',
        'users', now()),
    (gen_random_uuid(), 'users.activate',
        'Activate or Deactivate Users',
        'Toggle the active status of a user account.',
        'users', now()),
    (gen_random_uuid(), 'users.reset_password',
        'Reset User Passwords',
        'Generate a temporary password for a user.',
        'users', now()),
    (gen_random_uuid(), 'users.unlock',
        'Unlock Users',
        'Clear the login lockout on a user account.',
        'users', now()),
    -- roles module (4 permissions)
    (gen_random_uuid(), 'roles.read',
        'View Roles',
        'View roles and their assigned permissions.',
        'roles', now()),
    (gen_random_uuid(), 'roles.create',
        'Create Roles',
        'Create new roles.',
        'roles', now()),
    (gen_random_uuid(), 'roles.update',
        'Update Roles',
        'Edit role name, description, and active state.',
        'roles', now()),
    (gen_random_uuid(), 'roles.assign_permissions',
        'Assign Role Permissions',
        'Grant or revoke permissions on a role.',
        'roles', now()),
    -- org module (6 permissions)
    (gen_random_uuid(), 'org.departments.read',
        'View Departments',
        'List departments and view department details.',
        'org', now()),
    (gen_random_uuid(), 'org.departments.write',
        'Manage Departments',
        'Create and update departments.',
        'org', now()),
    (gen_random_uuid(), 'org.plants.read',
        'View Plants',
        'List plants and view plant details.',
        'org', now()),
    (gen_random_uuid(), 'org.plants.write',
        'Manage Plants',
        'Create and update plants.',
        'org', now()),
    (gen_random_uuid(), 'org.locations.read',
        'View Locations',
        'List locations and view location details.',
        'org', now()),
    (gen_random_uuid(), 'org.locations.write',
        'Manage Locations',
        'Create and update locations.',
        'org', now()),
    -- audit module (1 permission)
    (gen_random_uuid(), 'audit.read',
        'View Audit Log',
        'Read security audit events.',
        'audit', now());

-- Seed: role_permission assignments

-- SUPER_ADMIN receives all 18 permissions
INSERT INTO "role_permissions" ("role_id", "permission_id")
SELECT r.id, p.id
FROM "roles" r
CROSS JOIN "permissions" p
WHERE r.code = 'SUPER_ADMIN';

-- ADMIN receives 15 permissions:
--   all user-management + org-management + roles.read + audit.read
--   excludes: roles.create, roles.update, roles.assign_permissions
INSERT INTO "role_permissions" ("role_id", "permission_id")
SELECT r.id, p.id
FROM "roles" r
JOIN "permissions" p ON p.code IN (
    'users.read', 'users.create', 'users.update', 'users.assign_role',
    'users.activate', 'users.reset_password', 'users.unlock',
    'roles.read',
    'org.departments.read', 'org.departments.write',
    'org.plants.read', 'org.plants.write',
    'org.locations.read', 'org.locations.write',
    'audit.read'
)
WHERE r.code = 'ADMIN';

-- VIEWER receives 5 permissions (read-only)
INSERT INTO "role_permissions" ("role_id", "permission_id")
SELECT r.id, p.id
FROM "roles" r
JOIN "permissions" p ON p.code IN (
    'users.read',
    'roles.read',
    'org.departments.read',
    'org.plants.read',
    'org.locations.read'
)
WHERE r.code = 'VIEWER';

-- Data migration: backfill role_id for all existing users from the legacy role enum.
-- Runs after seed data so role UUIDs are available for lookup by code.
-- UserRole.ADMIN → SUPER_ADMIN (privileged users retain highest access)
-- UserRole.USER  → VIEWER     (standard users become read-only)
UPDATE "users"
SET "role_id" = (SELECT "id" FROM "roles" WHERE "code" = 'SUPER_ADMIN')
WHERE "role" = 'ADMIN';

UPDATE "users"
SET "role_id" = (SELECT "id" FROM "roles" WHERE "code" = 'VIEWER')
WHERE "role" = 'USER';
