-- Migration: add_incident_foundation (Unit 08 — 2026-07-01)
-- DDL generated by `prisma migrate diff --from-config-datasource --to-schema`
-- then manually reviewed and enhanced with:
--   1. CHECK constraints for non-empty strings (enforced in DB as secondary guard)
--   2. Seed: 10 incident permissions (identified by stable code, not UUID)
--   3. Seed: role_permission assignments using code-based subqueries
--
-- occurredAt future-check is enforced in application code, not as a DB constraint
-- (avoids clock-skew issues with now() in CHECK expressions).
--
-- onDelete: RESTRICT on incident_actions/comments/activities preserves history.
--
-- NEVER run prisma migrate reset against any company database.
-- Apply with: pnpm db:migrate:deploy

-- CreateEnum
CREATE TYPE "incident_severity" AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL');

-- CreateEnum
CREATE TYPE "incident_status" AS ENUM ('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'INVESTIGATION', 'ACTION_REQUIRED', 'RESOLVED', 'CLOSED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "incident_action_status" AS ENUM ('OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED');

-- CreateTable
CREATE TABLE "incident_sequences" (
    "year" INTEGER NOT NULL,
    "last_seq" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "incident_sequences_pkey" PRIMARY KEY ("year")
);

-- CreateTable
CREATE TABLE "incidents" (
    "id" UUID NOT NULL,
    "reference_number" VARCHAR(20) NOT NULL,
    "title" VARCHAR(300) NOT NULL,
    "description" TEXT NOT NULL,
    "severity" "incident_severity" NOT NULL,
    "status" "incident_status" NOT NULL DEFAULT 'DRAFT',
    "occurred_at" TIMESTAMPTZ(3) NOT NULL,
    "immediate_action" VARCHAR(2000),
    "reported_by_user_id" UUID NOT NULL,
    "reported_for_user_id" UUID,
    "affected_plant_id" UUID,
    "affected_location_id" UUID,
    "affected_department_id" UUID,
    "assigned_to_user_id" UUID,
    "reviewed_by_user_id" UUID,
    "root_cause" VARCHAR(2000),
    "investigation_summary" VARCHAR(4000),
    "resolution_summary" VARCHAR(4000),
    "resolved_by_user_id" UUID,
    "closed_by_user_id" UUID,
    "resolved_at" TIMESTAMPTZ(3),
    "closed_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "incidents_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "incident_actions" (
    "id" UUID NOT NULL,
    "incident_id" UUID NOT NULL,
    "title" VARCHAR(300) NOT NULL,
    "description" VARCHAR(2000),
    "status" "incident_action_status" NOT NULL DEFAULT 'OPEN',
    "assigned_to_user_id" UUID,
    "due_date" DATE,
    "completed_at" TIMESTAMPTZ(3),
    "completed_by_user_id" UUID,
    "created_by_user_id" UUID NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "incident_actions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "incident_comments" (
    "id" UUID NOT NULL,
    "incident_id" UUID NOT NULL,
    "author_user_id" UUID NOT NULL,
    "body" VARCHAR(5000) NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "incident_comments_pkey" PRIMARY KEY ("id")
);

-- CreateTable: incident_activities (no FK on actor_user_id — mirrors security_audit_events
-- so that deactivating a user never corrupts the incident timeline)
CREATE TABLE "incident_activities" (
    "id" UUID NOT NULL,
    "incident_id" UUID NOT NULL,
    "actor_user_id" UUID,
    "actor_name" VARCHAR(200),
    "event" VARCHAR(100) NOT NULL,
    "previous_status" "incident_status",
    "new_status" "incident_status",
    "metadata" JSONB,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "incident_activities_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "incidents_reference_number_key" ON "incidents"("reference_number");

-- CreateIndex
CREATE INDEX "incidents_status_created_at_idx" ON "incidents"("status", "created_at" DESC);

-- CreateIndex
CREATE INDEX "incidents_severity_status_idx" ON "incidents"("severity", "status");

-- CreateIndex
CREATE INDEX "incidents_reported_by_user_id_idx" ON "incidents"("reported_by_user_id");

-- CreateIndex
CREATE INDEX "incidents_assigned_to_user_id_idx" ON "incidents"("assigned_to_user_id");

-- CreateIndex
CREATE INDEX "incidents_affected_plant_id_idx" ON "incidents"("affected_plant_id");

-- CreateIndex
CREATE INDEX "incidents_affected_department_id_idx" ON "incidents"("affected_department_id");

-- CreateIndex
CREATE INDEX "incidents_resolved_at_idx" ON "incidents"("resolved_at");

-- CreateIndex
CREATE INDEX "incident_actions_incident_id_idx" ON "incident_actions"("incident_id");

-- CreateIndex
CREATE INDEX "incident_comments_incident_id_created_at_idx" ON "incident_comments"("incident_id", "created_at" ASC);

-- CreateIndex
CREATE INDEX "incident_activities_incident_id_created_at_idx" ON "incident_activities"("incident_id", "created_at" ASC);

-- AddForeignKey
ALTER TABLE "incidents" ADD CONSTRAINT "incidents_reported_by_user_id_fkey" FOREIGN KEY ("reported_by_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "incidents" ADD CONSTRAINT "incidents_reported_for_user_id_fkey" FOREIGN KEY ("reported_for_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "incidents" ADD CONSTRAINT "incidents_affected_plant_id_fkey" FOREIGN KEY ("affected_plant_id") REFERENCES "plants"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "incidents" ADD CONSTRAINT "incidents_affected_location_id_fkey" FOREIGN KEY ("affected_location_id") REFERENCES "locations"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "incidents" ADD CONSTRAINT "incidents_affected_department_id_fkey" FOREIGN KEY ("affected_department_id") REFERENCES "departments"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "incidents" ADD CONSTRAINT "incidents_assigned_to_user_id_fkey" FOREIGN KEY ("assigned_to_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "incidents" ADD CONSTRAINT "incidents_reviewed_by_user_id_fkey" FOREIGN KEY ("reviewed_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "incidents" ADD CONSTRAINT "incidents_resolved_by_user_id_fkey" FOREIGN KEY ("resolved_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "incidents" ADD CONSTRAINT "incidents_closed_by_user_id_fkey" FOREIGN KEY ("closed_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "incident_actions" ADD CONSTRAINT "incident_actions_incident_id_fkey" FOREIGN KEY ("incident_id") REFERENCES "incidents"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "incident_actions" ADD CONSTRAINT "incident_actions_assigned_to_user_id_fkey" FOREIGN KEY ("assigned_to_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "incident_actions" ADD CONSTRAINT "incident_actions_completed_by_user_id_fkey" FOREIGN KEY ("completed_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "incident_actions" ADD CONSTRAINT "incident_actions_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "incident_comments" ADD CONSTRAINT "incident_comments_incident_id_fkey" FOREIGN KEY ("incident_id") REFERENCES "incidents"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "incident_comments" ADD CONSTRAINT "incident_comments_author_user_id_fkey" FOREIGN KEY ("author_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "incident_activities" ADD CONSTRAINT "incident_activities_incident_id_fkey" FOREIGN KEY ("incident_id") REFERENCES "incidents"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- ============================================================================
-- CHECK constraints (manually added — Prisma does not generate these)
-- occurredAt future-check is enforced at the application layer, not here.
-- ============================================================================

ALTER TABLE "incidents"
    ADD CONSTRAINT "incidents_title_not_blank"
        CHECK (length(btrim("title")) > 0),
    ADD CONSTRAINT "incidents_description_not_blank"
        CHECK (length(btrim("description")) > 0),
    ADD CONSTRAINT "incidents_reference_number_format"
        CHECK ("reference_number" ~ '^INC-[0-9]{4}-[0-9]{6}$');

ALTER TABLE "incident_actions"
    ADD CONSTRAINT "incident_actions_title_not_blank"
        CHECK (length(btrim("title")) > 0);

ALTER TABLE "incident_comments"
    ADD CONSTRAINT "incident_comments_body_not_blank"
        CHECK (length(btrim("body")) > 0);

ALTER TABLE "incident_activities"
    ADD CONSTRAINT "incident_activities_event_not_blank"
        CHECK (length(btrim("event")) > 0);

-- ============================================================================
-- Seed: 10 incident permissions
-- Identified by stable code (ON CONFLICT DO NOTHING for idempotency).
-- UUIDs are generated by gen_random_uuid() to avoid hardcoded ID collisions.
-- ============================================================================

INSERT INTO "permissions" ("id", "code", "name", "description", "module", "created_at")
VALUES
    (gen_random_uuid(), 'incidents.read',
        'View Incidents',
        'List and view all incident records.',
        'incidents', now()),
    (gen_random_uuid(), 'incidents.create',
        'Report Incidents',
        'Submit new incident reports.',
        'incidents', now()),
    (gen_random_uuid(), 'incidents.update_own_draft',
        'Edit Own Draft',
        'Edit own DRAFT incidents before submission.',
        'incidents', now()),
    (gen_random_uuid(), 'incidents.review',
        'Review Incidents',
        'Triage submitted incidents and reclassify severity.',
        'incidents', now()),
    (gen_random_uuid(), 'incidents.assign',
        'Assign Incidents',
        'Assign an investigator to open incidents.',
        'incidents', now()),
    (gen_random_uuid(), 'incidents.investigate',
        'Investigate Incidents',
        'Lead investigation, record findings, and manage corrective actions.',
        'incidents', now()),
    (gen_random_uuid(), 'incidents.resolve',
        'Resolve Incidents',
        'Mark incidents as resolved with a resolution summary.',
        'incidents', now()),
    (gen_random_uuid(), 'incidents.close',
        'Close Incidents',
        'Close resolved incidents.',
        'incidents', now()),
    (gen_random_uuid(), 'incidents.comment',
        'Comment on Incidents',
        'Add comments to incident records.',
        'incidents', now()),
    (gen_random_uuid(), 'incidents.manage',
        'Manage Incidents',
        'Admin override: cancel, reopen, or change severity after review.',
        'incidents', now())
ON CONFLICT ("code") DO NOTHING;

-- ============================================================================
-- Seed: role_permission assignments using stable role/permission codes
-- ON CONFLICT DO NOTHING makes this idempotent.
-- ============================================================================

-- SUPER_ADMIN receives all 10 incident permissions
INSERT INTO "role_permissions" ("role_id", "permission_id")
SELECT r.id, p.id
FROM "roles" r
CROSS JOIN "permissions" p
WHERE r.code = 'SUPER_ADMIN'
  AND p.code IN (
      'incidents.read', 'incidents.create', 'incidents.update_own_draft',
      'incidents.review', 'incidents.assign', 'incidents.investigate',
      'incidents.resolve', 'incidents.close', 'incidents.comment',
      'incidents.manage'
  )
ON CONFLICT ("role_id", "permission_id") DO NOTHING;

-- ADMIN receives all 10 incident permissions
INSERT INTO "role_permissions" ("role_id", "permission_id")
SELECT r.id, p.id
FROM "roles" r
CROSS JOIN "permissions" p
WHERE r.code = 'ADMIN'
  AND p.code IN (
      'incidents.read', 'incidents.create', 'incidents.update_own_draft',
      'incidents.review', 'incidents.assign', 'incidents.investigate',
      'incidents.resolve', 'incidents.close', 'incidents.comment',
      'incidents.manage'
  )
ON CONFLICT ("role_id", "permission_id") DO NOTHING;

-- VIEWER receives 4 incident permissions (report and track own incidents)
INSERT INTO "role_permissions" ("role_id", "permission_id")
SELECT r.id, p.id
FROM "roles" r
CROSS JOIN "permissions" p
WHERE r.code = 'VIEWER'
  AND p.code IN (
      'incidents.read', 'incidents.create',
      'incidents.update_own_draft', 'incidents.comment'
  )
ON CONFLICT ("role_id", "permission_id") DO NOTHING;
