export { createPrismaClient } from './prisma-client';
export type { DatabaseClientConfig } from './prisma-client';

export { checkDatabaseHealth } from './database-health';
export type { DatabaseHealthResult, DatabaseHealthOk, DatabaseHealthUnavailable } from './database-health';

export type {
  PrismaClient,
  Department,
  Plant,
  Location,
  Role,
  Permission,
  RolePermission,
  User,
  UserSession,
  SecurityAuditEvent,
  IncidentSequence,
  Incident,
  IncidentAction,
  IncidentComment,
  IncidentActivity,
  TaskSequence,
  FactoryTask,
  FactoryTaskProgress,
  FactoryTaskComment,
  FactoryTaskActivity,
  MaintenanceSequence,
  MaintenanceRequest,
  MaintenanceRequestComment,
  MaintenanceRequestActivity,
  SafetyInspectionSequence,
  SafetyInspection,
  SafetyFinding,
  SafetyInspectionComment,
  SafetyInspectionActivity,
  ContractSequence,
  Contract,
  ContractComment,
  ContractActivity,
  ContractBoqItem,
  ContractBoqItemProductionStatus,
  ContractPayment,
  ContractWorkflowTask,
  ContractWorkflowTaskAttachment,
  ContractWorkflowTaskComment,
  ContractIssue,
  ContractClaim,
  ContractVariation,
  ContractVariationAttachment,
  ContractRisk,
  ContractDocumentObligation,
  ContractDocumentObligationAttachment,
  ContractCloseoutRequest,
  ContractCloseoutAttachment,
  ContractScheduleItem,
  ProductionSequence,
  ProductionLine,
  ProductionOrder,
  ProductionEntry,
  ProductionComment,
  ProductionActivity,
  UserModuleAccess,
  UserModuleDepartmentGrant,
} from './generated/prisma/client';
export {
  Prisma,
  IncidentSeverity,
  IncidentStatus,
  IncidentActionStatus,
  TaskPriority,
  TaskStatus,
  MaintenancePriority,
  MaintenanceStatus,
  InspectionStatus,
  FindingSeverity,
  FindingStatus,
  ContractStatus,
  ContractBoqMixDesignType,
  ContractBoqProductionStatus,
  ContractPaymentStatus,
  ContractScheduleStatus,
  ContractWorkflowTeam,
  ContractWorkflowTaskStatus,
  ContractWorkflowTaskPriority,
  ContractIssuePriority,
  ContractIssueStatus,
  ContractClaimType,
  ContractClaimStatus,
  ContractVariationStatus,
  ContractRiskLevel,
  ContractRiskResponse,
  ContractRiskStatus,
  ContractDocumentObligationCategory,
  ContractDocumentObligationStatus,
  ContractCloseoutRequestStatus,
  ContractScheduleStageKey,
  ProductionOrderStatus,
  ProductionEntryType,
  DepartmentAccessScope,
  ModuleIdentifier,
} from './generated/prisma/client';
