import { Injectable } from '@nestjs/common';
import { randomUUID } from 'node:crypto';
import { mkdir, writeFile } from 'node:fs/promises';
import { createReadStream, type ReadStream } from 'node:fs';
import * as path from 'node:path';
import { getApiEnv } from '../env';
import { WORKFLOW_ATTACHMENT_MAX_BYTES, WORKFLOW_ATTACHMENT_ALLOWED_MIME_TYPES } from './workflow-attachment-storage.service';

// ---------------------------------------------------------------------------
// CM-33 — safe local-disk storage for closeout request attachments. Structure
// mirrors WorkflowAttachmentStorageService (CM-32) exactly; validation rules
// (max size, allowed MIME types) are imported and reused directly rather than
// redefined, since this unit's spec sets no different rule for closeout
// documents. Kept as a separate class (not a shared generic) so CM-32's
// already-shipped, already-tested service is never touched by this unit.
// ---------------------------------------------------------------------------

export const CLOSEOUT_ATTACHMENT_MAX_BYTES = WORKFLOW_ATTACHMENT_MAX_BYTES;
export const CLOSEOUT_ATTACHMENT_ALLOWED_MIME_TYPES = WORKFLOW_ATTACHMENT_ALLOWED_MIME_TYPES;

@Injectable()
export class CloseoutAttachmentStorageService {
  private baseDir(): string {
    const configured = getApiEnv().closeoutAttachmentsDir;
    return path.isAbsolute(configured) ? configured : path.join(process.cwd(), configured);
  }

  /**
   * Stores a buffer under a per-closeout-request subfolder using a random,
   * collision-free filename — the caller-supplied original filename is never
   * used as the on-disk name (only recorded in the DB for display/download),
   * which eliminates path-traversal and overwrite risk entirely.
   */
  async save(closeoutRequestId: string, buffer: Buffer, originalFileName: string): Promise<{ fileName: string; storagePath: string }> {
    const ext = path.extname(originalFileName).slice(0, 10).replace(/[^a-zA-Z0-9.]/g, '');
    const fileName = `${randomUUID()}${ext}`;
    const relativePath = path.join(closeoutRequestId, fileName);
    const absoluteDir = path.join(this.baseDir(), closeoutRequestId);

    await mkdir(absoluteDir, { recursive: true });
    await writeFile(path.join(absoluteDir, fileName), buffer);

    return { fileName, storagePath: relativePath };
  }

  /**
   * Resolves a DB-stored relative path to an absolute filesystem path,
   * confined to the base upload directory — defense-in-depth even though
   * storagePath values are always generated by save(), never user input.
   */
  private resolveAbsolutePath(storagePath: string): string {
    const base = path.normalize(this.baseDir());
    const resolved = path.normalize(path.join(base, storagePath));
    if (!resolved.startsWith(base)) {
      throw new Error('Resolved attachment path escapes the storage root');
    }
    return resolved;
  }

  createReadStream(storagePath: string): ReadStream {
    return createReadStream(this.resolveAbsolutePath(storagePath));
  }
}
