import { Injectable } from '@nestjs/common';
import { randomUUID } from 'node:crypto';
import { mkdir, writeFile } from 'node:fs/promises';
import { createReadStream, type ReadStream } from 'node:fs';
import * as path from 'node:path';
import { getApiEnv } from '../env';
import { WORKFLOW_ATTACHMENT_MAX_BYTES, WORKFLOW_ATTACHMENT_ALLOWED_MIME_TYPES } from './workflow-attachment-storage.service';

// ---------------------------------------------------------------------------
// CM-63 — safe local-disk storage for Documents & Obligations supporting
// files. Structure mirrors WorkflowAttachmentStorageService (CM-32) /
// VariationAttachmentStorageService (CM-60C) exactly; validation rules (max
// size, allowed MIME types) are imported and reused directly rather than
// redefined, since this unit's spec sets the same rule (10MB; PDF/PNG/JPEG/
// XLSX/DOCX).
// ---------------------------------------------------------------------------

export const DOCUMENT_OBLIGATION_ATTACHMENT_MAX_BYTES = WORKFLOW_ATTACHMENT_MAX_BYTES;
export const DOCUMENT_OBLIGATION_ATTACHMENT_ALLOWED_MIME_TYPES = WORKFLOW_ATTACHMENT_ALLOWED_MIME_TYPES;

@Injectable()
export class DocumentObligationAttachmentStorageService {
  private baseDir(): string {
    const configured = getApiEnv().documentObligationAttachmentsDir;
    return path.isAbsolute(configured) ? configured : path.join(process.cwd(), configured);
  }

  /**
   * Stores a buffer under a per-document-obligation subfolder using a
   * random, collision-free filename — the caller-supplied original filename
   * is never used as the on-disk name (only recorded in the DB for display/
   * download), which eliminates path-traversal and overwrite risk entirely.
   */
  async save(documentObligationId: string, buffer: Buffer, originalFileName: string): Promise<{ fileName: string; storagePath: string }> {
    const ext = path.extname(originalFileName).slice(0, 10).replace(/[^a-zA-Z0-9.]/g, '');
    const fileName = `${randomUUID()}${ext}`;
    const relativePath = path.join(documentObligationId, fileName);
    const absoluteDir = path.join(this.baseDir(), documentObligationId);

    await mkdir(absoluteDir, { recursive: true });
    await writeFile(path.join(absoluteDir, fileName), buffer);

    return { fileName, storagePath: relativePath };
  }

  /**
   * Resolves a DB-stored relative path to an absolute filesystem path,
   * confined to the base upload directory — defense-in-depth even though
   * storagePath values are always generated by save(), never user input.
   */
  private resolveAbsolutePath(storagePath: string): string {
    const base = path.normalize(this.baseDir());
    const resolved = path.normalize(path.join(base, storagePath));
    if (!resolved.startsWith(base)) {
      throw new Error('Resolved attachment path escapes the storage root');
    }
    return resolved;
  }

  createReadStream(storagePath: string): ReadStream {
    return createReadStream(this.resolveAbsolutePath(storagePath));
  }
}
