import { Injectable } from '@nestjs/common';
import { randomUUID } from 'node:crypto';
import { mkdir, writeFile, unlink } from 'node:fs/promises';
import { createReadStream, type ReadStream } from 'node:fs';
import * as path from 'node:path';
import { getApiEnv } from '../env';
import { WORKFLOW_ATTACHMENT_MAX_BYTES, WORKFLOW_ATTACHMENT_ALLOWED_MIME_TYPES } from './workflow-attachment-storage.service';

// ---------------------------------------------------------------------------
// CM-71A — safe local-disk storage for Erection Method Statement supporting
// documents (method statement PDF, lift plan, risk assessment, approved shop
// drawing). Structure mirrors VariationAttachmentStorageService (CM-60C) /
// WorkflowAttachmentStorageService (CM-32) exactly; validation rules (max
// size, allowed MIME types) are imported and reused directly, not redefined.
// Adds deleteFile() — this is the first attachment feature in this app to
// support a real delete-attachment endpoint (see ContractErectionMethodStatementService),
// so a best-effort disk cleanup on delete is new, additive behavior; it
// never throws, matching logContractActivity's own "audit/cleanup writes
// must never turn an otherwise-successful request into a failure" rule —
// an orphaned file left on disk after a DB row is deleted is a cheap,
// recoverable cost; failing the user's delete request because a stray file
// couldn't be removed is not.
// ---------------------------------------------------------------------------

export const ERECTION_METHOD_STATEMENT_ATTACHMENT_MAX_BYTES = WORKFLOW_ATTACHMENT_MAX_BYTES;
export const ERECTION_METHOD_STATEMENT_ATTACHMENT_ALLOWED_MIME_TYPES = WORKFLOW_ATTACHMENT_ALLOWED_MIME_TYPES;

@Injectable()
export class ErectionMethodStatementAttachmentStorageService {
  private baseDir(): string {
    const configured = getApiEnv().erectionMethodStatementAttachmentsDir;
    return path.isAbsolute(configured) ? configured : path.join(process.cwd(), configured);
  }

  /**
   * Stores a buffer under a per-statement subfolder using a random,
   * collision-free filename — the caller-supplied original filename is never
   * used as the on-disk name (only recorded in the DB for display/download),
   * which eliminates path-traversal and overwrite risk entirely.
   */
  async save(methodStatementId: string, buffer: Buffer, originalFileName: string): Promise<{ fileName: string; storagePath: string }> {
    const ext = path.extname(originalFileName).slice(0, 10).replace(/[^a-zA-Z0-9.]/g, '');
    const fileName = `${randomUUID()}${ext}`;
    const relativePath = path.join(methodStatementId, fileName);
    const absoluteDir = path.join(this.baseDir(), methodStatementId);

    await mkdir(absoluteDir, { recursive: true });
    await writeFile(path.join(absoluteDir, fileName), buffer);

    return { fileName, storagePath: relativePath };
  }

  /**
   * Resolves a DB-stored relative path to an absolute filesystem path,
   * confined to the base upload directory — defense-in-depth even though
   * storagePath values are always generated by save(), never user input.
   */
  private resolveAbsolutePath(storagePath: string): string {
    const base = path.normalize(this.baseDir());
    const resolved = path.normalize(path.join(base, storagePath));
    if (!resolved.startsWith(base)) {
      throw new Error('Resolved attachment path escapes the storage root');
    }
    return resolved;
  }

  createReadStream(storagePath: string): ReadStream {
    return createReadStream(this.resolveAbsolutePath(storagePath));
  }

  /** Best-effort disk cleanup — deliberately never throws (see class doc comment). */
  async deleteFile(storagePath: string): Promise<void> {
    try {
      await unlink(this.resolveAbsolutePath(storagePath));
    } catch {
      // Deliberately swallowed — a missing/already-removed file must never fail the delete request.
    }
  }
}
