import { Injectable } from '@nestjs/common';
import { randomUUID } from 'node:crypto';
import { mkdir, writeFile, unlink } from 'node:fs/promises';
import { createReadStream, type ReadStream } from 'node:fs';
import * as path from 'node:path';
import { getApiEnv } from '../env';
import { WORKFLOW_ATTACHMENT_MAX_BYTES, WORKFLOW_ATTACHMENT_ALLOWED_MIME_TYPES } from './workflow-attachment-storage.service';

// ---------------------------------------------------------------------------
// CM-71G — safe local-disk storage for Erection Checklist (Step 6)
// documents: checklist form, material test reports, erection photos, QA/QC
// inspection records. Structure mirrors every other attachment storage
// service in this app exactly (ErectionStartAttachmentStorageService and
// its own predecessors); validation rules reused, not redefined. Delete
// support included, same as Steps 1-5.
// ---------------------------------------------------------------------------

export const ERECTION_CHECKLIST_ATTACHMENT_MAX_BYTES = WORKFLOW_ATTACHMENT_MAX_BYTES;
export const ERECTION_CHECKLIST_ATTACHMENT_ALLOWED_MIME_TYPES = WORKFLOW_ATTACHMENT_ALLOWED_MIME_TYPES;

@Injectable()
export class ErectionChecklistAttachmentStorageService {
  private baseDir(): string {
    const configured = getApiEnv().erectionChecklistAttachmentsDir;
    return path.isAbsolute(configured) ? configured : path.join(process.cwd(), configured);
  }

  /**
   * Stores a buffer under a per-checklist subfolder using a random,
   * collision-free filename — the caller-supplied original filename is never
   * used as the on-disk name (only recorded in the DB for display/download),
   * which eliminates path-traversal and overwrite risk entirely.
   */
  async save(checklistId: string, buffer: Buffer, originalFileName: string): Promise<{ fileName: string; storagePath: string }> {
    const ext = path.extname(originalFileName).slice(0, 10).replace(/[^a-zA-Z0-9.]/g, '');
    const fileName = `${randomUUID()}${ext}`;
    const relativePath = path.join(checklistId, fileName);
    const absoluteDir = path.join(this.baseDir(), checklistId);

    await mkdir(absoluteDir, { recursive: true });
    await writeFile(path.join(absoluteDir, fileName), buffer);

    return { fileName, storagePath: relativePath };
  }

  /**
   * Resolves a DB-stored relative path to an absolute filesystem path,
   * confined to the base upload directory — defense-in-depth even though
   * storagePath values are always generated by save(), never user input.
   */
  private resolveAbsolutePath(storagePath: string): string {
    const base = path.normalize(this.baseDir());
    const resolved = path.normalize(path.join(base, storagePath));
    if (!resolved.startsWith(base)) {
      throw new Error('Resolved attachment path escapes the storage root');
    }
    return resolved;
  }

  createReadStream(storagePath: string): ReadStream {
    return createReadStream(this.resolveAbsolutePath(storagePath));
  }

  /** Best-effort disk cleanup — deliberately never throws, matching the other erection attachment storage services. */
  async deleteFile(storagePath: string): Promise<void> {
    try {
      await unlink(this.resolveAbsolutePath(storagePath));
    } catch {
      // Deliberately swallowed — a missing/already-removed file must never fail the delete request.
    }
  }
}
