import { Injectable } from '@nestjs/common';
import { randomUUID } from 'node:crypto';
import { mkdir, writeFile } from 'node:fs/promises';
import { createReadStream, type ReadStream } from 'node:fs';
import * as path from 'node:path';
import { getApiEnv } from '../env';

// ---------------------------------------------------------------------------
// CM-32 — safe local-disk storage for workflow task attachments. No MinIO/S3
// is configured anywhere in this project (confirmed by audit), so this is a
// server-controlled local folder abstraction, easy to swap for object storage
// later without touching the DB schema (only storagePath's meaning changes).
// Binary data is NEVER stored in the database — only this metadata.
// ---------------------------------------------------------------------------

/** 10 MB — the exact limit specified for this unit. */
export const WORKFLOW_ATTACHMENT_MAX_BYTES = 10 * 1024 * 1024;

export const WORKFLOW_ATTACHMENT_ALLOWED_MIME_TYPES = [
  'application/pdf',
  'image/png',
  'image/jpeg',
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
] as const;

@Injectable()
export class WorkflowAttachmentStorageService {
  private baseDir(): string {
    const configured = getApiEnv().workflowAttachmentsDir;
    return path.isAbsolute(configured) ? configured : path.join(process.cwd(), configured);
  }

  /**
   * Stores a buffer under a per-task subfolder using a random, collision-free
   * filename — the caller-supplied original filename is never used as the
   * on-disk name (only recorded in the DB for display/download), which
   * eliminates path-traversal and overwrite risk entirely.
   */
  async save(taskId: string, buffer: Buffer, originalFileName: string): Promise<{ fileName: string; storagePath: string }> {
    const ext = path.extname(originalFileName).slice(0, 10).replace(/[^a-zA-Z0-9.]/g, '');
    const fileName = `${randomUUID()}${ext}`;
    const relativePath = path.join(taskId, fileName);
    const absoluteDir = path.join(this.baseDir(), taskId);

    await mkdir(absoluteDir, { recursive: true });
    await writeFile(path.join(absoluteDir, fileName), buffer);

    return { fileName, storagePath: relativePath };
  }

  /**
   * Resolves a DB-stored relative path to an absolute filesystem path,
   * confined to the base upload directory — defense-in-depth even though
   * storagePath values are always generated by save(), never user input.
   */
  private resolveAbsolutePath(storagePath: string): string {
    const base = path.normalize(this.baseDir());
    const resolved = path.normalize(path.join(base, storagePath));
    if (!resolved.startsWith(base)) {
      throw new Error('Resolved attachment path escapes the storage root');
    }
    return resolved;
  }

  createReadStream(storagePath: string): ReadStream {
    return createReadStream(this.resolveAbsolutePath(storagePath));
  }
}
