import { Injectable } from '@nestjs/common';
import { randomUUID } from 'node:crypto';
import { mkdir, writeFile, unlink } from 'node:fs/promises';
import { createReadStream, type ReadStream } from 'node:fs';
import * as path from 'node:path';
import { getApiEnv } from '../env';

// ---------------------------------------------------------------------------
// FMP-INC-01 — safe local-disk storage for Incident Evidence Attachments.
// Structure mirrors ErectionMethodStatementAttachmentStorageService /
// VariationAttachmentStorageService exactly (random UUID on-disk filename
// per parent-entity subfolder, path-traversal guard, best-effort disk
// cleanup on delete) — the same reused pattern, not a new storage style.
// Reused as-is; no MinIO/S3 (this codebase has neither configured
// anywhere — confirmed by FMP-UI-22's own audit).
//
// Allowed MIME types are a wider real-world evidence set than any single
// existing *_ATTACHMENT_ALLOWED_MIME_TYPES precedent (those only cover
// PDF/PNG/JPEG/XLSX/DOCX) — incident evidence realistically includes
// phone photos/videos and plain-text notes, so this defines its OWN
// constants rather than importing a narrower existing one. The allow-list
// design itself (only these exact MIME types pass; everything else,
// including .exe/.bat/.cmd/.ps1/.sh/.js/.mjs/.cjs/.html/.svg, is rejected
// by construction — never explicitly special-cased) is identical to every
// existing attachment feature's own `fileFilter`.
//
// Size limit: ticket allows up to 100MB for video "only if backend/server
// can safely handle it," otherwise one conservative limit. `FileInterceptor`
// buffers the whole upload into process memory (`file.buffer`) before this
// service ever writes it to disk — a 100MB cap per concurrent upload on a
// shared on-prem server with unknown concurrent load is not a safe default
// to assume without a memory-budget review this unit doesn't have the
// scope for. One conservative 25MB limit applies to every evidence file
// type, images/video/documents alike — the ticket's own explicit fallback
// instruction for exactly this situation.
// ---------------------------------------------------------------------------

export const INCIDENT_ATTACHMENT_MAX_BYTES = 25 * 1024 * 1024; // 25MB, all evidence types

export const INCIDENT_ATTACHMENT_ALLOWED_MIME_TYPES = [
  // Images
  'image/jpeg',
  'image/png',
  'image/webp',
  // Videos
  'video/mp4',
  'video/quicktime', // .mov
  'video/webm',
  // Documents
  'application/pdf',
  'application/msword', // .doc
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document', // .docx
  'application/vnd.ms-excel', // .xls
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', // .xlsx
  'text/csv',
  'text/plain', // .txt
] as const;

@Injectable()
export class IncidentAttachmentStorageService {
  private baseDir(): string {
    const configured = getApiEnv().incidentAttachmentsDir;
    return path.isAbsolute(configured) ? configured : path.join(process.cwd(), configured);
  }

  /**
   * Stores a buffer under a per-incident subfolder using a random,
   * collision-free filename — the caller-supplied original filename is
   * never used as the on-disk name (only recorded in the DB for display/
   * download), which eliminates path-traversal and overwrite risk entirely.
   */
  async save(incidentId: string, buffer: Buffer, originalFileName: string): Promise<{ fileName: string; storagePath: string }> {
    const ext = path.extname(originalFileName).slice(0, 10).replace(/[^a-zA-Z0-9.]/g, '');
    const fileName = `${randomUUID()}${ext}`;
    const relativePath = path.join(incidentId, fileName);
    const absoluteDir = path.join(this.baseDir(), incidentId);

    await mkdir(absoluteDir, { recursive: true });
    await writeFile(path.join(absoluteDir, fileName), buffer);

    return { fileName, storagePath: relativePath };
  }

  /**
   * Resolves a DB-stored relative path to an absolute filesystem path,
   * confined to the base upload directory — defense-in-depth even though
   * storagePath values are always generated by save(), never user input.
   */
  private resolveAbsolutePath(storagePath: string): string {
    const base = path.normalize(this.baseDir());
    const resolved = path.normalize(path.join(base, storagePath));
    if (!resolved.startsWith(base)) {
      throw new Error('Resolved attachment path escapes the storage root');
    }
    return resolved;
  }

  createReadStream(storagePath: string): ReadStream {
    return createReadStream(this.resolveAbsolutePath(storagePath));
  }

  /** Best-effort disk cleanup — deliberately never throws, matching every existing deleteFile()'s own rule: a missing/already-removed file must never fail the delete request. */
  async deleteFile(storagePath: string): Promise<void> {
    try {
      await unlink(this.resolveAbsolutePath(storagePath));
    } catch {
      // Deliberately swallowed.
    }
  }
}
